version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres_volume/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=CXC_DB
      - POSTGRES_USER=CXC_USER
      - POSTGRES_PASSWORD=CXC_PASSWORD

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis_volume/:/data/

  flask:
    container_name: flask
    build: .
    ports:
      - 5000:5000
    command: >
      bash -c "export FLASK_APP=SMS_service/sms_service &&
               flask run"

  cxc:
    container_name: cxc
    build: .
    # network_mode: 'host'
    restart: always
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=CXC_DB
      - POSTGRES_USER=CXC_USER
      - POSTGRES_PASSWORD=CXC_PASSWORD
    depends_on:
      - redis
      - postgres

  cxc_worker:
    container_name: cxc_worker
    build: .
    restart: always
    depends_on:
      - redis
      - cxc
    command: bash -c  "python manage.py makemigrations &&
                       python manage.py migrate &&
                       celery -A cryptoexchangecompare worker -l INFO"
    volumes:
      - ./volumes/cxc_worker/:/home/hossein/
    environment:
      - CELERY_BROKER=redis://redis:6379/0