# Generated by Django 4.0 on 2022-03-30 20:36

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('exchange', models.CharField(choices=[('Nobitex', 'Nobitex'), ('Wallex', 'Wallex'), ('Phinix', 'Phinix')], default='Nobitex', max_length=10)),
                ('token', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('crypto', models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('SHIB', 'SHIB'), ('ADA', 'ADA'), ('TRX', 'TRX'), ('DOGE', 'DOGE')], default='BTC', max_length=6)),
                ('exchange', models.CharField(choices=[('Nobitex', 'Nobitex'), ('Wallex', 'Wallex'), ('Phinix', 'Phinix')], default='Nobitex', max_length=10)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Success', 'Success')], max_length=16)),
                ('volume', models.FloatField()),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
